import BlogsWrapper from '@/Components/Blogs_lp/BlogsWrapper/BlogsWrapper';
import { Inter } from "next/font/google";
import './global.scss';
import Head from 'next/head';
const inter = Inter({ subsets: ['latin'], display: 'swap', adjustFontFallback: false})

export const metadata = {
  title: "MobilezMarket",
  description: "Generated by create next app",
  robots: {
      index: false,
      follow: false,
  },
};

export default function RootLayout({ children }) {
  const {robots} = metadata;
  return (
    <html lang="en">
      <Head>
      <meta name="robots"
                  content={`${robots.index ? 'index' : 'noindex'}, ${robots.follow ? 'follow' : 'nofollow'}`}/>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={inter.className}>
        <BlogsWrapper>
          {children}
        </BlogsWrapper>
      </body>
    </html>
  );
}
